name: "Terraform-plan-apply"

on:
    push:
        branches: ["main"]
    pull_request:

env:
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    TOKEN_TERRAFORM: ${{ secrets.TOKEN_TERRAFORM }}

jobs:
    terraform-plan:
        name: "Terraform Plan"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Azure login
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              run: terraform init

            - name: Terraform Plan
              run: terraform plan -input=false -var-file="terraform.tfvars" -out=tfplan

            - name: Upload Terraform Plan
              uses: actions/upload-artifact@v4
              with:
                  name: terraform-plan
                  path: tfplan

    terraform-apply:
        name: Terraform Apply
        needs: terraform-plan
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              run: terraform init

            - name: Download Terraform Plan
              uses: actions/download-artifact@v4
              with:
                  name: terraform-plan

            - name: Terraform Apply
              run: terraform apply -auto-approve tfplan

            - name: Terraform Apply
              run: |
                  export TF_VAR_github_token=$TOKEN_TERRAFORM
                  terraform apply -auto-approve
